import { test, expect } from '@playwright/test'
import { existsSync, globSync, readFileSync } from 'node:fs'

const fontPath = globSync('.tools/cargo/registry/src/*/cosmic-text-0.19.0/fonts/NotoSans-Regular.ttf')[0]

test('phase5 full static Japanese font loads from a real multi-MiB file and renders Japanese text', async ({ page }) => {
  const path = '.tools/fonts/phase5/NotoSansJP-Regular.ttf'
  test.skip(!existsSync(path), 'Run the explicitly opted-in CJK font fixture helper first')
  test.setTimeout(120000)
  const bytes = readFileSync(path)
  expect(bytes.length).toBeGreaterThan(1048576)
  await page.goto('/')
  await expect(page.getByRole('button', { name: 'Add text', exact: true })).toBeEnabled()
  await page.getByRole('button', { name: 'Add text', exact: true }).click()
  await page.getByRole('main', { name: 'Active slide canvas' }).getByRole('button', { name: /^Edit text-/ }).dblclick()
  const editor = page.getByRole('textbox', { name: 'Slide text editor', exact: true })
  await editor.fill('日本語の編集と復元。容量を確認します。')
  await editor.press('Control+Enter')
  await expect(editor).toHaveCount(0)
  await page.getByRole('button', { name: 'Fonts', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: 'Fonts', exact: true })
  await dialog.getByLabel('Font file').setInputFiles({ name: 'NotoSansJP-Regular.ttf', mimeType: 'font/ttf', buffer: bytes })
  await expect(dialog.getByRole('heading', { name: 'Noto Sans JP', exact: true })).toBeVisible({ timeout: 15000 })
  await expect(dialog).toContainText('12 MiB per face')
  await dialog.getByLabel('I have permission to embed this font and edit documents using it.').check()
  await dialog.getByRole('button', { name: 'Embed full font', exact: true }).click()
  await expect(dialog.getByRole('button', { name: 'Apply Noto Sans JP to selected text' })).toBeEnabled({ timeout: 30000 })
  await expect.poll(() => page.evaluate(() => [...document.fonts].filter(font => font.family.replaceAll('"', '') === 'Noto Sans JP' && font.status === 'loaded' && font.weight === '400').length)).toBeGreaterThan(0)
  await dialog.getByRole('button', { name: 'Apply Noto Sans JP to selected text' }).click()
  await expect(dialog.getByRole('status')).toContainText('Font assigned', { timeout: 30000 })
  await page.screenshot({ path: '.artifacts/phase5-cjk-font-desktop.png' })
  await page.setViewportSize({ width: 390, height: 844 })
  await expect.poll(() => dialog.evaluate(element => element.scrollWidth <= element.clientWidth)).toBe(true)
  await page.screenshot({ path: '.artifacts/phase5-cjk-font-mobile.png' })
  await dialog.getByRole('button', { name: 'Close dialog' }).click()
  await page.setViewportSize({ width: 1440, height: 960 })
  const text = page.getByRole('main', { name: 'Active slide canvas' }).getByText('日本語の編集と復元。容量を確認します。', { exact: true })
  await expect(text).toBeVisible()
  await page.evaluate(() => document.fonts.ready)
  await page.screenshot({ path: '.artifacts/phase5-cjk-text.png' })
  await expect(page.getByRole('alert')).toHaveCount(0)
})

for (const width of [1440, 390]) {
  test(`selected font consent, assignment and cleanup ${width}`, async ({ page }) => {
    test.skip(!fontPath, 'Local cosmic-text OFL Noto test fixture is not present')
    test.setTimeout(90000)
    await page.setViewportSize({ width, height: 960 })
    await page.goto('/')
    await expect(page.getByRole('button', { name: 'Fonts', exact: true })).toBeEnabled()
    await page.getByRole('button', { name: 'Add text', exact: true }).click()
    await page.getByRole('button', { name: 'Fonts', exact: true }).click()
    const dialog = page.getByRole('dialog', { name: 'Fonts', exact: true })
    await dialog.getByLabel('Font file').setInputFiles({ name: 'selected.ttf', mimeType: 'font/ttf', buffer: readFileSync(fontPath) })
    await expect(dialog.getByRole('heading', { name: 'Noto Sans', exact: true })).toBeVisible()
    await expect(dialog.getByRole('button', { name: 'Embed full font', exact: true })).toBeDisabled()
    await expect(dialog.getByLabel('I have permission to embed this font and edit documents using it.')).not.toBeChecked()
    await dialog.getByLabel('I have permission to embed this font and edit documents using it.').check()
    await dialog.getByRole('button', { name: 'Embed full font', exact: true }).click()
    await expect(dialog.getByRole('button', { name: 'Apply Noto Sans to selected text' })).toBeEnabled()
    await expect.poll(() => page.evaluate(() => [...document.fonts].filter((font) => font.family.replaceAll('"', '') === 'Noto Sans' && font.status === 'loaded').length)).toBe(1)
    await dialog.getByRole('button', { name: 'Apply Noto Sans to selected text' }).click()
    await expect(dialog.getByRole('status')).toContainText('Font assigned')
    await page.screenshot({ path: `.artifacts/g28-font-panel-${width}.png` })
    await dialog.getByRole('button', { name: 'Close dialog' }).click()
    await page.getByRole('button', { name: 'Undo', exact: true }).click()
    await page.getByRole('button', { name: 'Undo', exact: true }).click()
    await expect.poll(() => page.evaluate(() => [...document.fonts].filter((font) => font.family.replaceAll('"', '') === 'Noto Sans').length)).toBe(0)
    await page.getByRole('button', { name: 'Redo', exact: true }).click()
    await expect.poll(() => page.evaluate(() => [...document.fonts].filter((font) => font.family.replaceAll('"', '') === 'Noto Sans' && font.status === 'loaded').length)).toBe(1)
    await page.keyboard.press('Control+n')
    await page.getByRole('button', { name: 'Discard changes', exact: true }).click()
    await expect.poll(() => page.evaluate(() => [...document.fonts].filter((font) => font.family.replaceAll('"', '') === 'Noto Sans').length)).toBe(0)
  })
}

test('font picker rejects malformed bytes without loading a face or mutating history', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Fonts', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: 'Fonts', exact: true })
  await dialog.getByLabel('Font file').setInputFiles({ name: 'broken.ttf', mimeType: 'font/ttf', buffer: Buffer.from('wOF2 invalid') })
  await expect(dialog.getByRole('alert')).toContainText('TTF/OTF')
  await expect(dialog.getByRole('button', { name: 'Embed full font' })).toHaveCount(0)
  await dialog.getByRole('button', { name: 'Close dialog' }).click()
  await expect(page.getByRole('button', { name: 'Undo', exact: true })).toBeDisabled()
})